// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
    export interface GlobalComponents {
        Card: typeof import('./src/components/weathers/Common/Card.vue')['default'];
        CitySearch: typeof import('./src/components/CitySearch.vue')['default'];
        GPSPosition: typeof import('./src/components/GPSPosition.vue')['default'];
        Header: typeof import('./src/components/Header.vue')['default'];
        LocalCurrentWeather: typeof import('./src/components/weathers/LocalCurrentWeather.vue')['default'];
        LocalPM25: typeof import('./src/components/weathers/LocalPM25.vue')['default'];
        LocalPreWeather: typeof import('./src/components/weathers/LocalPreWeather.vue')['default'];
        Sidebar: typeof import('./src/components/Sidebar.vue')['default'];
        WeatherFanChart: typeof import('./src/components/weathers/Common/WeatherFanChart.vue')['default'];
        WeatherLineChart: typeof import('./src/components/weathers/Common/WeatherLineChart.vue')['default'];
        Worldmap: typeof import('./src/components/contents/worldmap.vue')['default'];
    }
}

export {};
